version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lunatic
      POSTGRES_PASSWORD: lunatic
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
